name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Preparation - Checkout code
        uses: actions/checkout@v4

      - name: Preparation - Set up OpenJDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilation - Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Checkstyle - Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon

      - name: Test - Run tests
        run: ./gradlew test --no-daemon